version: "3"
services:
  appsmith:
    image: appsmith/appsmith-ce:v1.91
    container_name: appsmith
    ports:
      - "8018:80"
      # - "443:443"
    volumes:
      - appsmith:/appsmith-stacks
    restart: unless-stopped
    networks:
      - personal_network

volumes:
  appsmith:

networks:
  personal_network:
    external: true
