services:
  postgrest:
    image: postgrest/postgrest:v14.1
    container_name: postgrest
    ports:
      - "8013:3000"
    environment:
      PGRST_SERVER_HOST: 0.0.0.0
      PGRST_DB_URI: postgres://postgres:postgres@host.docker.internal:5432/inventory
      PGRST_DB_ANON_ROLE: anon_user
      PGRST_SERVER_PORT: 3000
