services:
  postgrest:
    image: postgrest/postgrest:v14.1
    container_name: postgrest
    ports:
      - "8013:3000"
    environment:
      PGRST_SERVER_HOST: 0.0.0.0
      PGRST_DB_URI: postgres://postgres:postgres@postgres_main:5432/inventory
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_ANON_ROLE: anon_user
    networks:
      - personal_network

networks:
  personal_network:
    external: true
