services:
  anythingllm:
    image: mintplexlabs/anythingllm:1.9.0
    container_name: anythingllm
    ports:
      - "8013:3001"
    env_file:
      - .env
    volumes:
      - anythingllm_data:/app/server/storage
      - ./mcp.json:/app/server/storage/plugins/anythingllm_mcp_servers.json:ro
    environment:
      - STORAGE_DIR=/app/server/storage
    restart: unless-stopped
    networks:
      - personal_network
    extra_hosts:
      - "personal-01:host-gateway"
      - "akbarmr.dev:host-gateway"

volumes:
  anythingllm_data:

networks:
  personal_network:
    external: true
