services:
  anythingllm:
    image: mintplexlabs/anythingllm:1.9.0
    container_name: anythingllm
    ports:
      - "8013:3001"
    env_file:
      - .env
    volumes:
      - anythingllm_data:/app/server/storage
    environment:
      # This tells the application inside the container where to find its storage.
      - STORAGE_DIR=/app/server/storage
    restart: unless-stopped
    networks:
      - personal_network

volumes:
  anythingllm_data:

networks:
  personal_network:
    external: true
