services:
  3proxy:
    image: ghcr.io/tarampampam/3proxy:1
    environment:
      MAX_CONNECTIONS: 10000
      PROXY_PORT: 8000
      SOCKS_PORT: 8001
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
