name: frappe_docker
services:
  backend:
    container_name: erpnext_backend
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v15.87.0
    networks:
      - personal_network
    restart: unless-stopped
    volumes:
      - sites:/home/frappe/frappe-bench/sites
  configurator:
    container_name: erpnext_configurator
    command:
      - |
        ls -1 apps > sites/apps.txt; bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT; bench set-config -g redis_cache "redis://$$REDIS_CACHE"; bench set-config -g redis_queue "redis://$$REDIS_QUEUE"; bench set-config -g redis_socketio "redis://$$REDIS_QUEUE"; bench set-config -gp socketio_port $$SOCKETIO_PORT;
    depends_on:
      erpnext_redis:
        condition: service_started
    entrypoint:
      - bash
      - -c
    environment:
      DB_HOST: postgres_main
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      ADMIN_PASSWORD: admin
      REDIS_CACHE: erpnext_redis:6379/0
      REDIS_QUEUE: erpnext_redis:6379/1
      SOCKETIO_PORT: "9000"
    image: frappe/erpnext:v15.87.0
    networks:
      - personal_network
    restart: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites

  frontend:
    container_name: erpnext_frontend
    command:
      - nginx-entrypoint.sh
    depends_on:
      backend:
        condition: service_started
      websocket:
        condition: service_started
    environment:
      BACKEND: backend:8000
      CLIENT_MAX_BODY_SIZE: 50m
      FRAPPE_SITE_NAME_HEADER: $$host
      PROXY_READ_TIMEOUT: "120"
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
    image: frappe/erpnext:v15.87.0
    networks:
      - personal_network
    ports:
      - "8014:8080"
    restart: unless-stopped
    volumes:
      - sites:/home/frappe/frappe-bench/sites
  worker:
    container_name: erpnext_worker
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v15.87.0
    networks:
      - personal_network
    restart: unless-stopped
    volumes:
      - sites:/home/frappe/frappe-bench/sites
  erpnext_redis:
    container_name: erpnext_redis
    image: redis:6.2-alpine
    networks:
      - personal_network
    restart: unless-stopped
    volumes:
      - redis-data:/data
  scheduler:
    container_name: erpnext_scheduler
    command:
      - bench
      - schedule
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v15.87.0
    networks:
      - personal_network
    restart: unless-stopped
    volumes:
      - sites:/home/frappe/frappe-bench/sites
  websocket:
    container_name: erpnext_websocket
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    depends_on:
      configurator:
        condition: service_completed_successfully
    image: frappe/erpnext:v15.87.0
    networks:
      - personal_network
    restart: unless-stopped
    volumes:
      - sites:/home/frappe/frappe-bench/sites
networks:
  personal_network:
    external: true
volumes:
  redis-data:
  sites:
