services:
  inngest:
    image: inngest/inngest:v1.15.3
    command: "inngest start -u http://host.docker.internal:3010/api/inngest"
    ports:
      - "8288:8288"
      - "8289:8289"
    environment:
      - INNGEST_EVENT_KEY=736563726574 # secret
      - INNGEST_SIGNING_KEY=736563726574 # secret
      - INNGEST_POSTGRES_URI=postgres://postgres:postgres@postgres_main:5432/inngest
      - INNGEST_REDIS_URI=redis://inngest_redis:6379
    restart: unless-stopped
    depends_on:
      inngest_redis:
        condition: service_healthy
    networks:
      - personal_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  inngest_redis:
    container_name: inngest_redis
    image: redis:7.4.5-bookworm
    # ports:
    #   - "6379:6379"
    volumes:
      - inngest_redis:/data
    restart: unless-stopped
    networks:
      - personal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  inngest_redis:

networks:
  personal_network:
    external: true