services:
  inngest:
    image: inngest/inngest:v1.14.0
    command: "inngest start"
    ports:
      - "8288:8288"
      - "8289:8289"
    environment:
      - INNGEST_EVENT_KEY=736563726574 # secret
      - INNGEST_SIGNING_KEY=736563726574 # secret
      - INNGEST_POSTGRES_URI=postgres://postgres:postgres@postgres_main:5432/inngest
      - INNGEST_REDIS_URI=redis://inngest_redis:6379
    depends_on:
      inngest_redis:
        condition: service_healthy
    networks:
      - personal_network

  inngest_redis:
    container_name: inngest_redis
    image: redis:7.4.5-bookworm
    # ports:
    #   - "6379:6379"
    volumes:
      - inngest_redis:/data
    networks:
      - personal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  inngest_redis:

networks:
  personal_network:
    external: true